dist: bionic
sudo: required

language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ bionic multiverse"
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ bionic-backports universe"
    packages:
    - cmake
    - pkg-config
    - libogre-1.9-dev
    - libopenal-dev
    - libsfml-dev
    - libois-dev
    - libboost-filesystem-dev
    - libboost-locale-dev
    - libboost-program-options-dev
    - libboost-date-time-dev
    - libboost-thread-dev
    - libboost-system-dev
    - libboost-test-dev
    - libcegui-mk2-dev

script:
  - cmake . -DOD_BUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DCEGUI_INC_SEARCH_PATH=/usr/include/cegui-0.8.7/CEGUI
  - make -j2
  - make install DESTDIR=./install-root
  - ./scripts/unix/run_unit_tests.sh
